name: jsb-leaves-test
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: "RfECyC2yHSR8Jkf1DaMjLChs" # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: "ud5fRd9bUDJUdnGkigXGmJFK"  #Required
          vercel-project-id: "QmXvbJ89Ce9tcQ5XvkNF172JA4LLBVsDFeT8zRQQhUvAaj" #Required 
          working-directory: ./sub-directory
