name: jsb-leaves-test
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: 'RfECyC2yHSR8Jkf1DaMjLChs'
          github-token: ''
          vercel-org-id: 'ud5fRd9bUDJUdnGkigXGmJFK'
          vercel-project-id: 'QmXvbJ89Ce9tcQ5XvkNF172JA4LLBVsDFeT8zRQQhUvAaj'
          working-directory: ./sub-directory
